g6_friends_homepage:
    path:     /
    defaults: { _controller: G6FriendsBundle:Default:index }
    
g6_friends_login:
    path:     /login
    defaults: { _controller: G6FriendsBundle:User:login }
    
g6_friends_logout:
    path:     /logout
    defaults: { _controller: G6FriendsBundle:User:logout }
    
g6_friends_register:
    path:     /register
    defaults: { _controller: G6FriendsBundle:User:register }
    
g6_friends_user:
    path:     /user/{name}
    defaults: { _controller: G6FriendsBundle:User:user }

g6_friends_newpost:
    path:     /newpost
    defaults: { _controller: G6FriendsBundle:Post:new }
    
g6_friends_public_wall:
    path:     /public_wall
    defaults: { _controller: G6FriendsBundle:Default:wall }
    
g6_friends_post:
    path:     /post/{postId}
    defaults: { _controller: G6FriendsBundle:Post:view }
    
g6_friends_profile_info:
    path:     /profile_info
    defaults: { _controller: G6FriendsBundle:User:info }