G6\FriendsBundle\Entity\Post:
    type: entity
    table: post
    indexes:
        username:
            columns:
                - user_id
    id:
        postId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: post_id
            generator:
                strategy: IDENTITY
    fields:
        postContent:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: post_content
        postDate:
            type: datetime
            nullable: false
            comment: ''
            column: post_date
        likes:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: user_id
            orphanRemoval: false
    oneToMany:
        comment:
            targetEntity: Comment
            mappedBy: post
    lifecycleCallbacks: {  }
