G6\FriendsBundle\Entity\User:
    type: entity
    table: user
    id:
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: user_id
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        firstName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: last_name
        birthdate:
            type: date
            nullable: false
            comment: ''
        gender:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
        notes:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    oneToMany:
        post:
            targetEntity: Post
            mappedBy: user
    lifecycleCallbacks: {  }
